### Development config

hosts:
#  SANDBOX:
#    name: SANDBOX
#    type: org.olf.dcb.core.interaction.sierra.SierraLmsClient
#    client:
#      base-url: "https://sandbox.iii.com"
#      ingest: false
#      page-size: 100


#  FOLIO-TEST-INGEST:
#    name: Folio Test Ingest Source
#    type: org.olf.dcb.core.interaction.folio.FolioOaiPmhIngestSource
#    client:
#      base-url: "https://oai-host.com/oai/" # Note full path to OAI entry point.
#      metadataPrefix: marc21
#      recordSyntax: oai_dc
#      apikey: <secret>
#      ingest: true


# agencies:
#   testAgency1:
#     hostLms: sandbox

#micronaut:
#  security:
#    authentication: bearer
#    token:
#      jwt:
#        generator:
#          access-token:
#            expiration: 600
#        signatures:
#          secret:
#            generator:
#              secret: "${token.secret:secretsmustbeatleast256bitssothats32cha874hjkj3hjhhdd888dhhhhrs}"
#              base64: true
#              jws-algorithm: HS256
#          jwks:
#            keycloak:
#              url: ${KEYCLOAK_CERT_URL:""}

dcb:
  itemresolver:
    code: Geo
    
  #  index:
  #    name: mobius-si

#opensearch:
#  httpHosts: "http://localhost:9200"

#elasticsearch:
#  httpHosts: "http://localhost:9200"



